"""Add tracking columns to hasil_rekomendasi

Revision ID: 070f148c6c70
Revises: fa1ad19c7c24
Create Date: 2026-01-10 23:48:44.417889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070f148c6c70'
down_revision = 'fa1ad19c7c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('periode_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tingkat_kelas', sa.Enum('10', '11', '12', 'alumni'), nullable=True))
        batch_op.add_column(sa.Column('catatan_guru_bk', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'periodes', ['periode_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('catatan_guru_bk')
        batch_op.drop_column('tingkat_kelas')
        batch_op.drop_column('periode_id')

    # ### end Alembic commands ###
