"""Remove tampil_di siswa from kriteria model

Revision ID: 1b3819cf4442
Revises: 89ab9e1a567a
Create Date: 2026-03-08 21:12:15.179182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b3819cf4442'
down_revision = '89ab9e1a567a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.drop_column('tampil_di_siswa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tampil_di_siswa', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
