"""Remove nisn and email_verified_at from User model

Revision ID: 26202dc2d232
Revises: 9267b86cd7fc
Create Date: 2026-03-08 20:03:11.446608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26202dc2d232'
down_revision = '9267b86cd7fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))
        batch_op.drop_index(batch_op.f('nisn'))
        batch_op.drop_column('email')
        batch_op.drop_column('nisn')
        batch_op.drop_column('email_verified_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('nisn', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
        batch_op.add_column(sa.Column('email', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=True))
        batch_op.create_index(batch_op.f('nisn'), ['nisn'], unique=True)
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    # ### end Alembic commands ###
