"""Initial migration: tables from laravel schema

Revision ID: 8500bd177bb8
Revises: 
Create Date: 2026-01-10 23:01:30.868585

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8500bd177bb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False),
    sa.Column('major', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jurusan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_jurusan', sa.String(length=255), nullable=False),
    sa.Column('nama_jurusan', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode_jurusan')
    )
    op.create_table('kriteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode', sa.String(length=255), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('pertanyaan', sa.Text(), nullable=True),
    sa.Column('tipe_input', sa.Enum('number', 'select', 'likert', name='tipeinputenum'), nullable=False),
    sa.Column('opsi_pilihan', mysql.JSON(), nullable=True),
    sa.Column('atribut', sa.Enum('benefit', 'cost', name='atributenum'), nullable=False),
    sa.Column('kategori', sa.Enum('akademik', 'kuesioner', name='kategorienum'), nullable=False),
    sa.Column('sumber_nilai', sa.Enum('input_siswa', 'static_jurusan', name='sumbernilaienum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kode')
    )
    op.create_table('periodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_periode', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_periode')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pakar', 'siswa', name='roleenum'), nullable=False),
    sa.Column('kelas_saat_ini', sa.Enum('kelas_10', 'kelas_11', 'kelas_12', 'alumni', name='kelasenum'), nullable=False),
    sa.Column('nisn', sa.String(length=255), nullable=True),
    sa.Column('remember_token', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nisn'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bobot_kriterias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kriteria_id', sa.Integer(), nullable=False),
    sa.Column('jurusan_id', sa.Integer(), nullable=True),
    sa.Column('nilai_bobot', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['jurusan_id'], ['jurusan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kriteria_id'], ['kriteria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bwm_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pakar_id', sa.Integer(), nullable=False),
    sa.Column('best_criterion_id', sa.Integer(), nullable=False),
    sa.Column('worst_criterion_id', sa.Integer(), nullable=False),
    sa.Column('comparison_type', sa.Enum('best_to_others', 'others_to_worst', name='comparisontypeenum'), nullable=False),
    sa.Column('compared_criterion_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['best_criterion_id'], ['kriteria.id'], ),
    sa.ForeignKeyConstraint(['compared_criterion_id'], ['kriteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pakar_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worst_criterion_id'], ['kriteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hasil_rekomendasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('skor_studi', sa.Float(), nullable=True),
    sa.Column('skor_kerja', sa.Float(), nullable=True),
    sa.Column('skor_wirausaha', sa.Float(), nullable=True),
    sa.Column('keputusan_terbaik', sa.String(length=255), nullable=False),
    sa.Column('tanggal_hitung', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nilai_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('kriteria_id', sa.Integer(), nullable=False),
    sa.Column('nilai_input', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['kriteria_id'], ['kriteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['siswa_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nilai_siswa')
    op.drop_table('hasil_rekomendasi')
    op.drop_table('bwm_comparisons')
    op.drop_table('bobot_kriterias')
    op.drop_table('users')
    op.drop_table('periodes')
    op.drop_table('kriteria')
    op.drop_table('jurusan')
    op.drop_table('alumnis')
    # ### end Alembic commands ###
