"""Remove is_active from Pertanyaan model

Revision ID: 89ab9e1a567a
Revises: f6bd989b7b5b
Create Date: 2026-03-08 20:32:29.815167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89ab9e1a567a'
down_revision = 'f6bd989b7b5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.drop_column('tanggal_hitung')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('remember_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remember_token', mysql.VARCHAR(collation='utf8mb4_general_ci', length=100), nullable=True))

    with op.batch_alter_table('hasil_rekomendasi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanggal_hitung', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True))

    # ### end Alembic commands ###
