"""empty message

Revision ID: 9267b86cd7fc
Revises: 9e1f245e2006
Create Date: 2026-01-11 15:14:57.900996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9267b86cd7fc'
down_revision = '9e1f245e2006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.alter_column('penanggung_jawab',
               existing_type=mysql.ENUM('admin', 'pakar', 'siswa', collation='utf8mb4_general_ci'),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.alter_column('penanggung_jawab',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('admin', 'pakar', 'siswa', collation='utf8mb4_general_ci'),
               existing_nullable=True)

    # ### end Alembic commands ###
