"""empty message

Revision ID: 9e1f245e2006
Revises: 070f148c6c70
Create Date: 2026-01-11 12:42:51.245672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e1f245e2006'
down_revision = '070f148c6c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nilai_static_jurusans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurusan_id', sa.Integer(), nullable=False),
    sa.Column('kriteria_id', sa.Integer(), nullable=False),
    sa.Column('nilai', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['jurusan_id'], ['jurusan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kriteria_id'], ['kriteria.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nilai_static_jurusans')
    # ### end Alembic commands ###
