"""Initial migration from Laravel schema

Revision ID: fa1ad19c7c24
Revises: 8500bd177bb8
Create Date: 2026-01-10 23:41:15.382020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa1ad19c7c24'
down_revision = '8500bd177bb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tampil_di_siswa', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('penanggung_jawab', sa.Enum('admin', 'pakar', 'siswa', name='roleenum'), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_pakar', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('jurusan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'jurusan', ['jurusan_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('jurusan_id')
        batch_op.drop_column('jenis_pakar')

    with op.batch_alter_table('kriteria', schema=None) as batch_op:
        batch_op.drop_column('penanggung_jawab')
        batch_op.drop_column('tampil_di_siswa')

    op.drop_table('settings')
    # ### end Alembic commands ###
